/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT.
 */

package main

import (
	"flag"
	"fmt"
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
	"github.com/ying32/govcl/vcl/types/colors"
	"liangzi.local/qx/cmd"
	"strconv"
)

type TMainForm struct {
	*vcl.TForm
	year             *vcl.TEdit
	month, day, hour *vcl.TSpinEdit
	ok               *vcl.TButton
	ymdl             *vcl.TLabel

	kanStar, genStar, zhenStar, xunStar, liStar, kunStar, duiStar, qianStar, zhongStar      *vcl.TLabel //九星
	kanDoor, genDoor, zhenDoor, xunDoor, liDoor, kunDoor, duiDoor, qianDoor                 *vcl.TLabel //八门
	kanXiShen, genXiShen, zhenXiShen, xunXiShen, liXiShen, kunXiShen, duiXiShen, qianXiShen *vcl.TLabel //喜神
	huangHeiZi, huangHeiChou, huangHeiYin, huangHeiMao, huangHeiChen, huangHeiSi            *vcl.TLabel //时辰黄黑
	huangHeiWu, huangHeiWei, huangHeiShen, huangHeiYou, huangHeiXu, huangHeiHai             *vcl.TLabel //时辰黄黑
	jieLuZi, jieLuChou, jieLuYin, jieLuMao, jieLuChen, jieLuSi                              *vcl.TLabel //截路空
	jieLuWu, jieLuWei, jieLuShen, jieLuYou, jieLuXu, jieLuHai                               *vcl.TLabel //截路空
	tianYiZi, tianYiChou, tianYiYin, tianYiMao, tianYiChen, tianYiSi                        *vcl.TLabel //天乙贵人
	tianYiWu, tianYiWei, tianYiShen, tianYiYou, tianYiXu, tianYiHai                         *vcl.TLabel //天乙贵人
	local1, local8, local3, local4, local9, local2, local7, local6, local5                  *vcl.TLabel //未动方位
}

func main() {
	flag.BoolVar(&printVersion, "version", false, "print program build version")
	flag.Parse()

	if printVersion {
		cmd.PrintVersion()
	}
	vcl.RunApp(&mainForm)
}
func (f *TMainForm) OnFormCreate(sender vcl.IObject) {
	const (
		width  = 800
		height = 800
	)
	f.SetWidth(width)
	f.SetHeight(height)
	f.SetWindowState(types.WsMinimized)
	f.SetCaption("日家奇门")
	f.Font().SetSize(13)
	f.SetShowHint(true)
	f.local()
	f.draw()

	f.OnFormGet(sender)
}
func (f *TMainForm) draw() {
	const (
		top = 150
	)
	line := `------------`
	line = fmt.Sprintf("%s%s%s%s%s%s",
		line, line, line, line, line, line)
	h1 := vcl.NewLabel(f)
	h1.SetParent(f)
	h1.SetLeft(30)
	h1.SetTop(top)
	h1.SetCaption(line)

	h2 := vcl.NewLabel(f)
	h2.SetParent(f)
	h2.SetLeft(30)
	h2.SetTop(top * 2)
	h2.SetCaption(line)

	vline := `|`
	vline = fmt.Sprintf("%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n",
		vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline, vline)
	v1 := vcl.NewLabel(f)
	v1.SetParent(f)
	v1.SetTop(30)
	v1.SetLeft(top)
	v1.SetCaption(vline)

	v2 := vcl.NewLabel(f)
	v2.SetParent(f)
	v2.SetTop(30)
	v2.SetLeft(top + 130)
	v2.SetCaption(vline)

}

//获取输入信息
func (f *TMainForm) OnFormGet(sender vcl.IObject) {
	const height = 800
	const step = 33
	f.year = vcl.NewEdit(f)
	f.year.SetParent(f)
	f.year.SetTop(height - step)
	f.year.SetWidth(2 * step)
	f.year.Font().SetSize(11)
	f.year.SetTextBuf(strconv.Itoa(t.Year()))

	f.month = vcl.NewSpinEdit(f)
	f.month.SetParent(f)
	f.month.SetTop(height - step)
	f.month.SetLeft(2 * step)
	f.month.SetWidth(2 * step)
	f.month.Font().SetSize(11)
	f.month.SetMinValue(1)
	f.month.SetMaxValue(12)

	f.day = vcl.NewSpinEdit(f)
	f.day.SetParent(f)
	f.day.SetTop(height - step)
	f.day.SetLeft(4 * step)
	f.day.SetWidth(2 * step)
	f.day.Font().SetSize(11)
	f.day.SetMinValue(1)
	f.day.SetMaxValue(31)

	f.hour = vcl.NewSpinEdit(f)
	f.hour.SetParent(f)
	f.hour.SetTop(height - step)
	f.hour.SetLeft(6 * step)
	f.hour.SetWidth(2 * step)
	f.hour.Font().SetSize(11)
	f.hour.SetMinValue(0)
	f.hour.SetMaxValue(24)

	f.ok = vcl.NewButton(f)
	f.ok.SetParent(f)
	f.ok.SetTop(height - step)
	f.ok.SetLeft(8 * step)
	f.ok.SetWidth(step)
	f.ok.SetHeight(step)
	f.ok.Font().SetSize(13)
	f.ok.Font().SetColor(colors.ClBlack)
	f.ok.SetCaption("ok")
	f.ok.SetOnClick(f.OnFormBtnOK)
	//
	ys := f.year.Text()[:4]
	y, _ := strconv.Atoi(ys)
	m := f.month.Value()
	d := f.day.Value()
	h := f.hour.Value()
	f.OnFormDefault(y, int(m), int(d), int(h))
	//
	License := vcl.NewButton(f)
	License.SetParent(f)
	License.SetTop(height - step)
	License.SetLeft(f.ok.Left() + 40)
	License.SetHeight(step)
	License.SetCaption("关于")
	License.SetOnClick(f.OnBtnAbout)
}

func (f *TMainForm) OnFormBtnOK(sender vcl.IObject) {
	ys := f.year.Text()[:4]
	y, _ := strconv.Atoi(ys)
	m := f.month.Value()
	d := f.day.Value()
	h := f.hour.Value()
	f.OnFormSpecifiedTime(y, int(m), int(d), int(h))
}

func (f *TMainForm) OnBtnAbout(sender vcl.IObject) {
	s := `
日家奇门
0.0.0
作者邮箱: bGlhbmd6aTIwMjFAeWFuZGV4LmNvbQo="
`
	vcl.ShowMessageFmt("%s", s)
}

//var MIT = `本软件在 MIT 许可下发布
//版权所有 (c) 2021 Aquarian-Age。
//特此授予任何人免费获得本软件副本和相关文档文件（“软件”）的许
//可，不受限制地处理本软件，包括但不限于使用、复制、修改、合并
//的权利、发布、分发、再许可和/或出售软件的副本，并允许向其提
//供软件的人员这样做，但须符合以下条件：
//
//上述版权声明和本许可声明应包含在软件的所有副本或重要部分中。
//本软件按“原样”提供，不提供任何形式的明示或暗示的保证，包括
//但不限于适销性、特定用途的适用性和不侵权的保证。在任何情况
//下，作者或版权持有人均不对任何索赔、损害或其他责任承担责任，
//无论是在合同诉讼、侵权行为或其他方面，由软件或软件的使用或
//使用或其他原因引起的或与之相关的软件。
//本软件不包含任何担保
//`
