/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT.
 */

package main

import "time"

const (
	form2h = 700
	form2w = 600
)

var (
	printVersion bool
	mainForm     *TMainForm
	t            = time.Now().Local()
)

const (
	top1  = 20
	top2  = 170
	top3  = 320
	left1 = 30
	left2 = 160
	left3 = 290
	hTop  = 30
	left4 = 420
	left5 = 500
	left6 = 560
)
