/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 *  Licensed under MIT.
 */

package main

import (
	"log"
	"runtime"
	"sort"
	"strconv"

	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/rtl"
	"github.com/ying32/govcl/vcl/types"
	"github.com/ying32/govcl/vcl/types/colors"
	"liangzi.local/qx/pkg/sizhu"
)

type TForm struct {
	*vcl.TForm
	seMonth, seDay, seHour                                           *vcl.TSpinEdit //月日时
	seYear                                                           *vcl.TEdit     //输入年
	shiShenl, shiShenY, shiShenM, shiShenD, shiShenH                 *vcl.TLabel    //十神
	gzl, ygzl, mgzl, dgzl, hgzl                                      *vcl.TLabel    //四柱
	cangGanl                                                         *vcl.TLabel
	cangGanY1, cangGanY2, cangGanY3, shiShenY1, shiShenY2, shiShenY3 *vcl.TLabel //藏干
	cangGanM1, cangGanM2, cangGanM3, shiShenM1, shiShenM2, shiShenM3 *vcl.TLabel //藏干
	cangGanD1, cangGanD2, cangGanD3, shiShenD1, shiShenD2, shiShenD3 *vcl.TLabel //藏干
	cangGanH1, cangGanH2, cangGanH3, shiShenH1, shiShenH2, shiShenH3 *vcl.TLabel //藏干

	shuaiWangl, shuaiWangY, shuaiWangM, shuaiWangD, shuaiWangH *vcl.TLabel //衰旺
	naYinl, naYinY, naYinM, naYinD, naYinH                     *vcl.TLabel //纳音
	taiYuan, mingGong                                          *vcl.TLabel //胎元 命宫
	zhongQi                                                    *vcl.TLabel //中气
	btn                                                        *vcl.TButton
	sz                                                         *sizhu.SiZhu
}

var mainForm *TForm

func main() {
	vcl.RunApp(&mainForm)
}
func (f *TForm) OnFormCreate(sender vcl.IObject) {
	f.SetWidth(600)
	f.SetHeight(600)
	f.SetCaption("四柱")
	f.ScreenCenter()
	f.SetShowHint(true)
	f.getInput(sender)
	f.initLables()
	f.about()
}

func (f *TForm) getInput(vcl.IObject) {
	yearl := vcl.NewLabel(f)
	yearl.SetParent(f)
	yearl.SetLeft(10)
	yearl.SetTop(10)
	yearl.Font().SetSize(13)
	yearl.Font().SetColor(colors.ClBlack)
	yearl.SetCaption("阳历年")

	monthl := vcl.NewLabel(f)
	monthl.SetParent(f)
	monthl.SetLeft(yearl.Left() + yearl.Width())
	monthl.SetTop(yearl.Top())
	monthl.Font().SetSize(13)
	monthl.Font().SetColor(colors.ClBlack)
	monthl.SetCaption("阳历月")

	dayl := vcl.NewLabel(f)
	dayl.SetParent(f)
	dayl.SetLeft(monthl.Left() + monthl.Width())
	dayl.SetTop(monthl.Top())
	dayl.Font().SetSize(13)
	dayl.Font().SetColor(colors.ClBlack)
	dayl.SetCaption("阳历日")

	hourl := vcl.NewLabel(f)
	hourl.SetParent(f)
	hourl.SetLeft(dayl.Left() + dayl.Width())
	hourl.SetTop(dayl.Top())
	hourl.Font().SetSize(13)
	hourl.Font().SetColor(colors.ClBlack)
	hourl.SetCaption("阳历时")

	f.seYear = vcl.NewEdit(f)
	f.seYear.SetParent(f)
	f.seYear.SetLeft(10)
	f.seYear.SetTop(yearl.Top() + 30)
	f.seYear.SetWidth(60)
	f.seYear.SetText("")

	f.seMonth = vcl.NewSpinEdit(f)
	f.seMonth.SetParent(f)
	f.seMonth.SetLeft(f.seYear.Left() + f.seYear.Width() + 10)
	f.seMonth.SetTop(f.seYear.Top())
	f.seMonth.SetMinValue(1)
	f.seMonth.SetMaxValue(12)

	f.seDay = vcl.NewSpinEdit(f)
	f.seDay.SetParent(f)
	f.seDay.SetLeft(f.seMonth.Left() + f.seMonth.Width() + 10)
	f.seDay.SetTop(f.seMonth.Top())
	f.seDay.SetMinValue(1)
	f.seDay.SetMaxValue(31)

	f.seHour = vcl.NewSpinEdit(f)
	f.seHour.SetParent(f)
	f.seHour.SetLeft(f.seDay.Left() + f.seDay.Width() + 10)
	f.seHour.SetTop(f.seDay.Top())
	f.seHour.SetMinValue(0)
	f.seHour.SetMaxValue(23)

	f.btn = vcl.NewButton(f)
	f.btn.SetParent(f)
	f.btn.SetLeft(f.seHour.Left() + f.seHour.Width() + 3)
	f.btn.SetTop(f.seHour.Top())
	f.btn.Font().SetSize(13)
	if runtime.GOOS == "linux" {
		f.btn.SetHeight(30)
	}
	f.btn.Font().SetColor(colors.ClRed)
	f.btn.SetCaption("排四柱")
	f.btn.SetOnClick(f.OnFormBtn)

}
func (f *TForm) OnFormBtn(vcl.IObject) {
	y, err := strconv.Atoi(f.seYear.Text()[:4])
	if err != nil {
		log.Println("年数字异常")
	}
	m, err := strconv.Atoi(f.seMonth.Text())
	if err != nil {
		log.Println("月数字异常")
	}
	d, err := strconv.Atoi(f.seDay.Text())
	if err != nil {
		log.Println("日数字异常")
	}
	h, err := strconv.Atoi(f.seHour.Text())
	if err != nil {
		log.Println("时间数字异常")
	}
	f.sz = sizhu.NewSiZhu(y, m, d, h)

	f.ShowLabels()
}
func (f *TForm) initLables() {
	f.shiShenl = vcl.NewLabel(f)
	f.shiShenl.SetParent(f)
	f.shiShenY = vcl.NewLabel(f)
	f.shiShenY.SetParent(f)
	f.shiShenM = vcl.NewLabel(f)
	f.shiShenM.SetParent(f)
	f.shiShenD = vcl.NewLabel(f)
	f.shiShenD.SetParent(f)
	f.shiShenH = vcl.NewLabel(f)
	f.shiShenH.SetParent(f)
	//
	f.gzl = vcl.NewLabel(f)
	f.gzl.SetParent(f)
	f.ygzl = vcl.NewLabel(f)
	f.ygzl.SetParent(f)
	f.mgzl = vcl.NewLabel(f)
	f.mgzl.SetParent(f)
	f.dgzl = vcl.NewLabel(f)
	f.dgzl.SetParent(f)
	f.hgzl = vcl.NewLabel(f)
	f.hgzl.SetParent(f)
	//
	f.cangGanl = vcl.NewLabel(f)
	f.cangGanl.SetParent(f)
	f.cangGanY1 = vcl.NewLabel(f)
	f.cangGanY1.SetParent(f)
	f.cangGanY2 = vcl.NewLabel(f)
	f.cangGanY2.SetParent(f)
	f.cangGanY3 = vcl.NewLabel(f)
	f.cangGanY3.SetParent(f)
	f.shiShenY1 = vcl.NewLabel(f)
	f.shiShenY1.SetParent(f)
	f.shiShenY2 = vcl.NewLabel(f)
	f.shiShenY2.SetParent(f)
	f.shiShenY3 = vcl.NewLabel(f)
	f.shiShenY3.SetParent(f)
	//
	f.cangGanM1 = vcl.NewLabel(f)
	f.cangGanM1.SetParent(f)
	f.cangGanM2 = vcl.NewLabel(f)
	f.cangGanM2.SetParent(f)
	f.cangGanM3 = vcl.NewLabel(f)
	f.cangGanM3.SetParent(f)
	f.shiShenM1 = vcl.NewLabel(f)
	f.shiShenM1.SetParent(f)
	f.shiShenM2 = vcl.NewLabel(f)
	f.shiShenM2.SetParent(f)
	f.shiShenM3 = vcl.NewLabel(f)
	f.shiShenM3.SetParent(f)
	//
	f.cangGanD1 = vcl.NewLabel(f)
	f.cangGanD1.SetParent(f)
	f.cangGanD2 = vcl.NewLabel(f)
	f.cangGanD2.SetParent(f)
	f.cangGanD3 = vcl.NewLabel(f)
	f.cangGanD3.SetParent(f)
	f.shiShenD1 = vcl.NewLabel(f)
	f.shiShenD1.SetParent(f)
	f.shiShenD2 = vcl.NewLabel(f)
	f.shiShenD2.SetParent(f)
	f.shiShenD3 = vcl.NewLabel(f)
	f.shiShenD3.SetParent(f)
	//
	f.cangGanH1 = vcl.NewLabel(f)
	f.cangGanH1.SetParent(f)
	f.cangGanH2 = vcl.NewLabel(f)
	f.cangGanH2.SetParent(f)
	f.cangGanH3 = vcl.NewLabel(f)
	f.cangGanH3.SetParent(f)
	f.shiShenH1 = vcl.NewLabel(f)
	f.shiShenH1.SetParent(f)
	f.shiShenH2 = vcl.NewLabel(f)
	f.shiShenH2.SetParent(f)
	f.shiShenH3 = vcl.NewLabel(f)
	f.shiShenH3.SetParent(f)
	//
	f.shuaiWangl = vcl.NewLabel(f)
	f.shuaiWangl.SetParent(f)
	f.shuaiWangY = vcl.NewLabel(f)
	f.shuaiWangY.SetParent(f)
	f.shuaiWangM = vcl.NewLabel(f)
	f.shuaiWangM.SetParent(f)
	f.shuaiWangD = vcl.NewLabel(f)
	f.shuaiWangD.SetParent(f)
	f.shuaiWangH = vcl.NewLabel(f)
	f.shuaiWangH.SetParent(f)
	//
	f.naYinl = vcl.NewLabel(f)
	f.naYinl.SetParent(f)
	f.naYinY = vcl.NewLabel(f)
	f.naYinY.SetParent(f)
	f.naYinM = vcl.NewLabel(f)
	f.naYinM.SetParent(f)
	f.naYinD = vcl.NewLabel(f)
	f.naYinD.SetParent(f)
	f.naYinH = vcl.NewLabel(f)
	f.naYinH.SetParent(f)
	//
	f.taiYuan = vcl.NewLabel(f)
	f.taiYuan.SetParent(f)
	f.mingGong = vcl.NewLabel(f)
	f.mingGong.SetParent(f)
	f.zhongQi = vcl.NewLabel(f)
	f.zhongQi.SetParent(f)
}
func (f *TForm) ShowLabels() {
	dgz := f.sz.Dgz
	nianZhu := f.sz.NianZhu()
	shiShenYS, shiShenYhintS := nianZhu.ShiShen(dgz)
	yueZhu := f.sz.YueZhu()
	shiShenMS, shiShenMhintS := yueZhu.ShiShen(dgz)
	riZhu := f.sz.RiZhu()
	shiZhu := f.sz.ShiZhu()
	shiShiShenHS, shiShenHhints := shiZhu.ShiShen(dgz)

	f.shiShenl.Refresh()
	f.shiShenl.SetLeft(f.seYear.Left())
	f.shiShenl.SetTop(f.btn.Top() + 30)
	f.shiShenl.Font().SetSize(13)
	f.shiShenl.Font().SetColor(colors.ClSkyblue)
	f.shiShenl.SetCaption("十神")

	f.gzl.Refresh()
	f.gzl.SetLeft(f.shiShenl.Left())
	f.gzl.SetTop(f.shiShenl.Height() + f.shiShenl.Top() + 3)
	f.gzl.Font().SetSize(13)
	f.gzl.Font().SetColor(colors.ClSkyblue)
	f.gzl.SetCaption("四柱")

	f.cangGanl.Refresh()
	f.cangGanl.SetLeft(f.gzl.Left())
	f.cangGanl.SetTop(f.gzl.Top() + f.gzl.Height() + 3)
	f.cangGanl.Font().SetSize(13)
	f.cangGanl.Font().SetColor(colors.ClSkyblue)
	f.cangGanl.SetCaption("藏干")

	f.shiShenY.Refresh()
	f.shiShenY.SetLeft(f.shiShenl.Left() + f.shiShenl.Width() + 10)
	f.shiShenY.SetTop(f.shiShenl.Top())
	f.shiShenY.Font().SetSize(13)
	f.shiShenY.Font().SetColor(colors.ClBlue)
	f.shiShenY.SetCaption(shiShenYS)
	f.shiShenY.SetHint(shiShenYhintS)

	f.shiShenM.Refresh()
	f.shiShenM.SetLeft(f.shiShenY.Left() + f.shiShenY.Width() + 90)
	f.shiShenM.SetTop(f.shiShenY.Top())
	f.shiShenM.Font().SetSize(13)
	f.shiShenM.Font().SetColor(colors.ClBlue)
	f.shiShenM.SetCaption(shiShenMS)
	f.shiShenM.SetHint(shiShenMhintS)

	f.shiShenD.Refresh()
	f.shiShenD.SetLeft(f.shiShenM.Left() + f.shiShenM.Width() + 90)
	f.shiShenD.SetTop(f.shiShenM.Top())
	f.shiShenD.Font().SetSize(13)
	f.shiShenD.Font().SetColor(colors.ClBlue)
	f.shiShenD.Font().SetColor(colors.ClRed)
	f.shiShenD.SetCaption("日主")

	f.shiShenH.Refresh()
	f.shiShenH.SetLeft(f.shiShenD.Left() + f.shiShenD.Width() + 90)
	f.shiShenH.SetTop(f.shiShenD.Top())
	f.shiShenH.Font().SetSize(13)
	f.shiShenH.Font().SetColor(colors.ClBlue)
	f.shiShenH.SetCaption(shiShiShenHS)
	f.shiShenH.SetHint(shiShenHhints)
	//
	ygzs, mgzs, dgzs, hgzs := f.sz.Ygz, f.sz.Mgz, f.sz.Dgz, f.sz.Hgz

	f.ygzl.Refresh()
	f.ygzl.SetLeft(f.shiShenY.Left())
	f.ygzl.SetTop(f.gzl.Top())
	f.ygzl.Font().SetSize(13)
	f.ygzl.SetCaption(ygzs)

	f.mgzl.Refresh()
	f.mgzl.Font().SetSize(13)
	f.mgzl.SetLeft(f.shiShenM.Left())
	f.mgzl.SetTop(f.ygzl.Top())
	f.mgzl.SetCaption(mgzs)

	f.dgzl.Refresh()
	f.dgzl.SetLeft(f.shiShenD.Left())
	f.dgzl.SetTop(f.mgzl.Top())
	f.dgzl.Font().SetSize(13)
	f.dgzl.SetCaption(dgzs)

	f.hgzl.Refresh()
	f.hgzl.SetLeft(f.shiShenH.Left())
	f.hgzl.SetTop(f.dgzl.Top())
	f.hgzl.Font().SetSize(13)
	f.hgzl.SetCaption(hgzs)
	//
	cgy := nianZhu.CangGan()
	cgm := yueZhu.CangGan()
	cgd := riZhu.CangGan()
	cgh := shiZhu.CangGan()

	sy1s := sizhu.ShiShen(cgy.A, dgz)
	sy2s := sizhu.ShiShen(cgy.B, dgz)
	sy3s := sizhu.ShiShen(cgy.C, dgz)
	sm1s := sizhu.ShiShen(cgm.A, dgz)
	sm2s := sizhu.ShiShen(cgm.B, dgz)
	sm3s := sizhu.ShiShen(cgm.C, dgz)
	sd1s := sizhu.ShiShen(cgd.A, dgz)
	sd2s := sizhu.ShiShen(cgd.B, dgz)
	sd3s := sizhu.ShiShen(cgd.C, dgz)
	sh1s := sizhu.ShiShen(cgh.A, dgz)
	sh2s := sizhu.ShiShen(cgh.B, dgz)
	sh3s := sizhu.ShiShen(cgh.C, dgz)

	f.cangGanY1.Refresh()
	f.cangGanY1.SetLeft(f.ygzl.Left() + f.ygzl.Width()/2)
	f.cangGanY1.SetTop(f.cangGanl.Top())
	f.cangGanY1.Font().SetSize(13)
	f.cangGanY1.Font().SetColor(colors.ClBlue)
	f.cangGanY1.SetCaption(cgy.A)

	f.shiShenY1.Refresh()
	f.shiShenY1.SetLeft(f.cangGanY1.Left() + f.cangGanY1.Width() + 6)
	f.shiShenY1.SetTop(f.cangGanY1.Top())
	f.shiShenY1.Font().SetSize(13)
	f.shiShenY1.Font().SetColor(colors.ClBlue)
	f.shiShenY1.SetCaption(sy1s)

	f.cangGanY2.Refresh()
	f.cangGanY2.SetLeft(f.cangGanY1.Left())
	f.cangGanY2.SetTop(f.cangGanY1.Top() + f.cangGanY1.Height())
	f.cangGanY2.Font().SetSize(13)
	f.cangGanY2.Font().SetColor(colors.ClBlue)
	f.cangGanY2.SetCaption(cgy.B)

	f.shiShenY2.Refresh()
	f.shiShenY2.SetLeft(f.cangGanY2.Left() + f.cangGanY2.Width() + 6)
	f.shiShenY2.SetTop(f.cangGanY2.Top())
	f.shiShenY2.Font().SetSize(13)
	f.shiShenY2.Font().SetColor(colors.ClBlue)
	f.shiShenY2.SetCaption(sy2s)

	f.cangGanY3.Refresh()
	f.cangGanY3.SetLeft(f.cangGanY2.Left())
	f.cangGanY3.SetTop(f.cangGanY2.Top() + f.cangGanY2.Height())
	f.cangGanY3.Font().SetSize(13)
	f.cangGanY3.Font().SetColor(colors.ClBlue)
	f.cangGanY3.SetCaption(cgy.C)

	f.shiShenY3.Refresh()
	f.shiShenY3.SetLeft(f.cangGanY3.Left() + f.cangGanY3.Width() + 6)
	f.shiShenY3.SetTop(f.cangGanY3.Top())
	f.shiShenY3.Font().SetSize(13)
	f.shiShenY3.Font().SetColor(colors.ClBlue)
	f.shiShenY3.SetCaption(sy3s)
	//
	f.cangGanM1.Refresh()
	f.cangGanM1.SetLeft(f.mgzl.Left() + f.mgzl.Width()/2)
	f.cangGanM1.SetTop(f.cangGanl.Top())
	f.cangGanM1.Font().SetSize(13)
	f.cangGanM1.Font().SetColor(colors.ClBlue)
	f.cangGanM1.SetCaption(cgm.A)

	f.shiShenM1.Refresh()
	f.shiShenM1.SetLeft(f.cangGanM1.Left() + f.cangGanM1.Width() + 6)
	f.shiShenM1.SetTop(f.cangGanM1.Top())
	f.shiShenM1.Font().SetSize(13)
	f.shiShenM1.Font().SetColor(colors.ClBlue)
	f.shiShenM1.SetCaption(sm1s)

	f.cangGanM2.Refresh()
	f.cangGanM2.SetLeft(f.cangGanM1.Left())
	f.cangGanM2.SetTop(f.cangGanM1.Top() + f.cangGanM1.Height())
	f.cangGanM2.Font().SetSize(13)
	f.cangGanM2.Font().SetColor(colors.ClBlue)
	f.cangGanM2.SetCaption(cgm.B)

	f.shiShenM2.Refresh()
	f.shiShenM2.SetLeft(f.cangGanM2.Left() + f.cangGanM2.Width() + 6)
	f.shiShenM2.SetTop(f.cangGanM2.Top())
	f.shiShenM2.Font().SetSize(13)
	f.shiShenM2.Font().SetColor(colors.ClBlue)
	f.shiShenM2.SetCaption(sm2s)

	f.cangGanM3.Refresh()
	f.cangGanM3.SetLeft(f.cangGanM2.Left())
	f.cangGanM3.SetTop(f.cangGanM2.Top() + f.cangGanM2.Height())
	f.cangGanM3.Font().SetSize(13)
	f.cangGanM3.Font().SetColor(colors.ClBlue)
	f.cangGanM3.SetCaption(cgm.C)

	f.shiShenM3.Refresh()
	f.shiShenM3.SetLeft(f.cangGanM3.Left() + f.cangGanM3.Width() + 6)
	f.shiShenM3.SetTop(f.cangGanM3.Top())
	f.shiShenM3.Font().SetSize(13)
	f.shiShenM3.Font().SetColor(colors.ClBlue)
	f.shiShenM3.SetCaption(sm3s)
	//
	f.cangGanD1.Refresh()
	f.cangGanD1.SetLeft(f.dgzl.Left() + f.dgzl.Width()/2)
	f.cangGanD1.SetTop(f.cangGanl.Top())
	f.cangGanD1.Font().SetSize(13)
	f.cangGanD1.Font().SetColor(colors.ClBlue)
	f.cangGanD1.SetCaption(cgd.A)

	f.shiShenD1.Refresh()
	f.shiShenD1.SetLeft(f.cangGanD1.Left() + f.cangGanD1.Width() + 6)
	f.shiShenD1.SetTop(f.cangGanD1.Top())
	f.shiShenD1.Font().SetSize(13)
	f.shiShenD1.Font().SetColor(colors.ClBlue)
	f.shiShenD1.SetCaption(sd1s)

	f.cangGanD2.Refresh()
	f.cangGanD2.SetLeft(f.cangGanD1.Left())
	f.cangGanD2.SetTop(f.cangGanD1.Top() + f.cangGanD1.Height())
	f.cangGanD2.Font().SetSize(13)
	f.cangGanD2.Font().SetColor(colors.ClBlue)
	f.cangGanD2.SetCaption(cgd.B)

	f.shiShenD2.Refresh()
	f.shiShenD2.SetLeft(f.cangGanD2.Left() + f.cangGanD2.Width() + 6)
	f.shiShenD2.SetTop(f.cangGanD2.Top())
	f.shiShenD2.Font().SetSize(13)
	f.shiShenD2.Font().SetColor(colors.ClBlue)
	f.shiShenD2.SetCaption(sd2s)

	f.cangGanD3.Refresh()
	f.cangGanD3.SetLeft(f.cangGanD2.Left())
	f.cangGanD3.SetTop(f.cangGanD2.Top() + f.cangGanD2.Height())
	f.cangGanD3.Font().SetSize(13)
	f.cangGanD3.Font().SetColor(colors.ClBlue)
	f.cangGanD3.SetCaption(cgd.C)

	f.shiShenD3.Refresh()
	f.shiShenD3.SetLeft(f.cangGanD3.Left() + f.cangGanD3.Width() + 6)
	f.shiShenD3.SetTop(f.cangGanD3.Top())
	f.shiShenD3.Font().SetSize(13)
	f.shiShenD3.Font().SetColor(colors.ClBlue)
	f.shiShenD3.SetCaption(sd3s)
	//
	f.cangGanH1.Refresh()
	f.cangGanH1.SetLeft(f.hgzl.Left() + f.hgzl.Width()/2)
	f.cangGanH1.SetTop(f.cangGanl.Top())
	f.cangGanH1.Font().SetSize(13)
	f.cangGanH1.Font().SetColor(colors.ClBlue)
	f.cangGanH1.SetCaption(cgh.A)

	f.shiShenH1.Refresh()
	f.shiShenH1.SetLeft(f.cangGanH1.Left() + f.cangGanH1.Width() + 6)
	f.shiShenH1.SetTop(f.cangGanH1.Top())
	f.shiShenH1.Font().SetSize(13)
	f.shiShenH1.Font().SetColor(colors.ClBlue)
	f.shiShenH1.SetCaption(sh1s)

	f.cangGanH2.Refresh()
	f.cangGanH2.SetLeft(f.cangGanH1.Left())
	f.cangGanH2.SetTop(f.cangGanH1.Top() + f.cangGanH1.Height())
	f.cangGanH2.Font().SetSize(13)
	f.cangGanH2.Font().SetColor(colors.ClBlue)
	f.cangGanH2.SetCaption(cgh.B)

	f.shiShenH2.Refresh()
	f.shiShenH2.SetLeft(f.cangGanH2.Left() + f.cangGanH2.Width() + 6)
	f.shiShenH2.SetTop(f.cangGanH2.Top())
	f.shiShenH2.Font().SetSize(13)
	f.shiShenH2.Font().SetColor(colors.ClBlue)
	f.shiShenH2.SetCaption(sh2s)

	f.cangGanH3.Refresh()
	f.cangGanH3.SetLeft(f.cangGanH2.Left())
	f.cangGanH3.SetTop(f.cangGanH2.Top() + f.cangGanH2.Height())
	f.cangGanH3.Font().SetSize(13)
	f.cangGanH3.Font().SetColor(colors.ClBlue)
	f.cangGanH3.SetCaption(cgh.C)

	f.shiShenH3.Refresh()
	f.shiShenH3.SetLeft(f.cangGanH3.Left() + f.cangGanH3.Width() + 6)
	f.shiShenH3.SetTop(f.cangGanH3.Top())
	f.shiShenH3.Font().SetSize(13)
	f.shiShenH3.Font().SetColor(colors.ClBlue)
	f.shiShenH3.SetCaption(sh3s)
	//
	lyh := f.shiShenY3.Height() + f.shiShenY3.Top()
	lmh := f.shiShenM3.Height() + f.shiShenM3.Top()
	ldh := f.shiShenD3.Height() + f.shiShenD3.Top()
	lhh := f.shiShenH3.Height() + f.shiShenH3.Top()
	harr := []int{int(lyh), int(lmh), int(ldh), int(lhh)}
	sort.Ints(harr)
	heigh := harr[len(harr)-1]

	f.shuaiWangl.Refresh()
	f.shuaiWangl.SetLeft(f.cangGanl.Left())
	f.shuaiWangl.SetTop(int32(heigh))
	f.shuaiWangl.Font().SetSize(13)
	f.shuaiWangl.Font().SetColor(colors.ClSkyblue)
	f.shuaiWangl.SetCaption("衰旺")

	swy := nianZhu.ShuaiWang(dgz)
	swm := yueZhu.ShuaiWang(dgz)
	swd := riZhu.ShuaiWang(dgz)
	swh := shiZhu.ShuaiWang(dgz)

	f.shuaiWangY.Refresh()
	f.shuaiWangM.Refresh()
	f.shuaiWangD.Refresh()
	f.shuaiWangH.Refresh()

	f.shuaiWangY.SetLeft(f.ygzl.Left())
	f.shuaiWangY.SetTop(f.shuaiWangl.Top())
	f.shuaiWangY.Font().SetSize(13)
	f.shuaiWangY.Font().SetColor(colors.ClBlack)
	f.shuaiWangY.SetCaption(swy)

	f.shuaiWangM.SetLeft(f.mgzl.Left())
	f.shuaiWangM.SetTop(f.shuaiWangl.Top())
	f.shuaiWangM.Font().SetSize(13)
	f.shuaiWangM.Font().SetColor(colors.ClBlack)
	f.shuaiWangM.SetCaption(swm)

	f.shuaiWangD.SetLeft(f.dgzl.Left())
	f.shuaiWangD.SetTop(f.shuaiWangl.Top())
	f.shuaiWangD.Font().SetSize(13)
	f.shuaiWangD.Font().SetColor(colors.ClBlack)
	f.shuaiWangD.SetCaption(swd)

	f.shuaiWangH.SetLeft(f.hgzl.Left())
	f.shuaiWangH.SetTop(f.shuaiWangl.Top())
	f.shuaiWangH.Font().SetSize(13)
	f.shuaiWangH.Font().SetColor(colors.ClBlack)
	f.shuaiWangH.SetCaption(swh)
	//
	f.naYinY.Refresh()
	f.naYinM.Refresh()
	f.naYinD.Refresh()
	f.naYinH.Refresh()

	naYiny := nianZhu.NaYin()
	naYinm := yueZhu.NaYin()
	naYind := riZhu.NaYin()
	naYinh := shiZhu.NaYin()

	f.naYinl.SetLeft(f.shuaiWangl.Left())
	f.naYinl.SetTop(f.shuaiWangl.Top() + f.shuaiWangl.Height() + 3)
	f.naYinl.Font().SetSize(13)
	f.naYinl.Font().SetColor(colors.ClSkyblue)
	f.naYinl.SetCaption("纳音")

	f.naYinY.SetLeft(f.ygzl.Left())
	f.naYinY.SetTop(f.naYinl.Top())
	f.naYinY.Font().SetSize(13)
	f.naYinY.Font().SetColor(colors.ClBlack)
	f.naYinY.SetCaption(naYiny)

	f.naYinM.SetLeft(f.mgzl.Left())
	f.naYinM.SetTop(f.naYinl.Top())
	f.naYinM.Font().SetSize(13)
	f.naYinM.Font().SetColor(colors.ClBlack)
	f.naYinM.SetCaption(naYinm)

	f.naYinD.SetLeft(f.dgzl.Left())
	f.naYinD.SetTop(f.naYinl.Top())
	f.naYinD.Font().SetSize(13)
	f.naYinD.Font().SetColor(colors.ClBlack)
	f.naYinD.SetCaption(naYind)

	f.naYinH.SetLeft(f.hgzl.Left())
	f.naYinH.SetTop(f.naYinl.Top())
	f.naYinH.Font().SetSize(13)
	f.naYinH.Font().SetColor(colors.ClBlack)
	f.naYinH.SetCaption(naYinh)
	//
	f.taiYuan.Refresh()
	f.mingGong.Refresh()
	taiYuanS := f.sz.TaiYuan()
	mingGongS := f.sz.MingGong()
	f.taiYuan.SetLeft(f.naYinl.Left())
	f.taiYuan.SetTop(f.naYinl.Top() + f.naYinl.Height() + 3)
	f.taiYuan.Font().SetSize(13)
	f.taiYuan.Font().SetColor(colors.ClBlack)
	f.taiYuan.SetCaption("胎元: " + taiYuanS)

	f.mingGong.SetLeft(f.taiYuan.Left())
	f.mingGong.SetTop(f.taiYuan.Top() + f.taiYuan.Height() + 3)
	f.mingGong.Font().SetSize(13)
	f.mingGong.Font().SetColor(colors.ClBlack)
	f.mingGong.SetCaption("命宫: " + mingGongS)

	f.zhongQi.Refresh()
	zhongQiS := f.sz.ZhongQiName + f.sz.ZhongQiT
	f.zhongQi.SetLeft(f.mingGong.Left())
	f.zhongQi.SetTop(f.mingGong.Top() + f.mingGong.Height() + 3)
	f.zhongQi.Font().SetSize(11)
	f.zhongQi.Font().SetColor(colors.ClSkyblue)
	f.zhongQi.SetCaption(`中气: ` + zhongQiS)
}
func (f *TForm) about() {
	linklbl := vcl.NewLinkLabel(f)
	linklbl.SetParent(f)
	linklbl.SetTop(560)
	linklbl.SetLeft(10)
	linklbl.SetCaption("<a href=\"https://github.com/Aquarian-Age/ccal/releases\">下载</a>")
	linklbl.Font().SetSize(13)
	linklbl.SetOnLinkClick(func(sender vcl.IObject, link string, linktype types.TSysLinkType) {
		rtl.SysOpen(link)
	})
}
